export const CREATE_JOKE_SUCCESS = "CREATE_JOKE_SUCCESS";
export const LOAD_JOKE_SUCCESS = "LOAD_JOKE_SUCCESS";
export const UPDATE_JOKE_SUCCESS = "UPDATE_JOKE_SUCCESS";
export const DELETE_JOKE_SUCCESS = "DELETE_JOKE_SUCCESS";
export const GET_RANDOM_JOKE_SUCCESS = "GET_RANDOM_JOKE_SUCCESS";
export const PAGINATION_JOKE_SUCCESS = "PAGINATION_JOKE_SUCCESS";
export const ERRORTOST_JOKE_FAILED = "ERRORTOST_JOKE_FAILED";
